### ISSUE TITLE
[help] backlog.time has probably been changed

### ISSUE THREAD

**Issue by SanskritFritz** [karan42/quasselsearch#2]
Maybe the format of the field ```backlog.time``` has been changed since you wrote this script, because now the dates in the output are quite messed up and also I had to change the following line:
https://github.com/karan42/quasselsearch/blob/44c1c274a8ece27d4a182524227215bc4aaec9a0/quasselsearch.sh#L13
to 
```
endtime="2000000000000"
```
to make the script work without dates as parameters. I could not make it work with dates as parameters, like
```
./quasselsearch.sh -n 'SanskritFritz' -c '#archlinux' -q 'frank' -e '2019-02-03 11:23:11'
```
while this works:
```
./quasselsearch.sh -n 'SanskritFritz' -c '#archlinux' -q 'frank'
```

I'm stuck here, because I don't know how to handle the values in ```backlog.time```.

**Comment by karan42** [comment]
Hi,
Can you post what the current timestamp looks like mangled? And yes you might be right the field might have changed, since I haven't used quassel or this script in a long time.

**Comment by SanskritFritz** [comment]
This message:
```[2019.02.25 13:09:10] <SanskritFritz> testmessage```

The corresponding line in the database:
```674827 | 1551096550918 | 14 | 1 | 1 | 13949 | testmessage |  ```

Thanks for caring :smile:

**Comment by karan42** [comment]
Hey, 
So after digging into it, the buffer.time has indeed been updated. They are now using 64bit to represent time, the script was written using 32bit time. So this just leads to everything being mangled for sure. https://github.com/quassel/quassel/blob/bc3c84736898ef185b70ec37a95fa664392276cb/ChangeLog <- line 64 

You'll need to change the conversions from readable time to epoch time and vice versa. Here's a hint https://serverfault.com/questions/151109/how-to-get-current-unix-time-in-milliseconds-in-bash

If you can't fix this, wait for the weekend, i'll do it. :) I'm just happy I have a user haha

**Comment by SanskritFritz** [comment]
I probably could do this, but I'll wait for you. I'll be a faithful user :smile:

**Comment by SanskritFritz** [comment]
I'll even create an archlinux package for this :wink:

**Comment by SanskritFritz** [comment]
Well? Have you got the time?

**Comment by karan42** [comment]
If you could do the change, I'll merge it. I do not have the time for a
month atleast, as i moved to weechat, and stopped using quassel about a
year ago. So it'll take me a lot of time, which i can only spare after a
month.

**Comment by SanskritFritz** [comment]
It's allright, I'll see what I can do. In the meanwhile I discovered Quasselgrep, which actually supersedes Quasselsearch, but somehow I like yours better.

**Comment by karan42** [comment]
Fixed with a helpful commit from @tiffany352

**Comment by SanskritFritz** [comment]
Amazing, thank you @tiffany352 !

**Comment by SanskritFritz** [comment]
https://aur.archlinux.org/packages/quasselsearch-git/
:smile:
